### PR TITLE
Use migrations

### PR DESCRIPTION
**Pull request by VicDeo**
:exclamation:  this PR adds dependency on **ownCloud 10.0.3+**

- Fixed unit-tests
- Switched to migrations
- Bigintified tables

### Before
```
| oc_lucene_status | CREATE TABLE `oc_lucene_status` (
  `fileid` int(11) NOT NULL DEFAULT '0',
  `status` varchar(1) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`fileid`),
  KEY `status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |

```

### This branch - update from prev version
```
| oc_lucene_status | CREATE TABLE `oc_lucene_status` (
  `fileid` bigint(20) NOT NULL DEFAULT '0',
  `status` varchar(1) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`fileid`),
  KEY `status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
```

### This branch - clean install
```
| oc_lucene_status | CREATE TABLE `oc_lucene_status` (
  `fileid` bigint(20) unsigned NOT NULL,
  `status` varchar(1) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`fileid`),
  KEY `status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |

```

### CODE REVIEW

**Comment by VicDeo** [comment]
Stable10: #128

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@VicDeo some test bootstrap problem ?
```
Fatal error:  Class 'OC_User_Database' not found in /home/travis/build/owncloud/core/apps/search_lucene/tests/unit/testcase.php on line 70
```

**Comment by DeepDiver1975** [comment]
> Class 'OC_User_Database'

fix le tests - this class is dead

**Comment by DeepDiver1975** [comment]
this whole test bootstrap code needs to be re-implemented - https://github.com/owncloud/search_lucene/blob/6b536d02975f15fa4da9a7b0dbb78e13794edd36/tests/unit/testcase.php#L66-L78

try to use the UserTrait

**Comment by VicDeo** [comment]
@PVince81 @DeepDiver1975 finally fixed

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
