### PR TITLE
Fix scrolling to search result

### LINKED ISSUE #88: Can't open search result
Steps to reproduce:
Search in OwnCloud fulltext search in users root folder for a string in a document.
A few pdf-documents are displayed. Click on one of them to open them.

Expected behaviour:
Possibility 1: Open the pdf-preview to show the selected file.
Possibility 2: Jump in folder location and scroll to the right file & mark them.

Actual behaviour:
Only jump in the file-location folder. No autoscroll or file mark. I've search the file in this folder again manually.

Server Host info:
Ubuntu-Server 14.04.2 LTS Trusty Tahr - Release amd64
Apache/2.4.7 (Ubuntu)
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
OwnCloud 8.0.3 stable

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #88

### CODE REVIEW

**Comment by VicDeo** [comment]
@scream88 FYI

**Comment by scream88** [comment]
Thank you. :-)

**Comment by VicDeo** [comment]
@karlitschek requesting backport to stable8.1/stable8

**Comment by karlitschek** [comment]
please backport!

**Pull request merged**
