### PR TITLE
Update pdfparser to 0.9.23

### PR DESCRIPTION
**Pull request by VicDeo**
Changelog excerpt:
0.9.23
Memory fixes

0.9.22
Fix infinite loop and memory overload.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@LukasReschke @butonic please review - THX

**Comment by DeepDiver1975** [comment]
> @LukasReschke @butonic please review - THX

PING

**Comment by VicDeo** [comment]
@butonic any opinion finally?

**Comment by LukasReschke** [comment]
:+1: from my side

**Comment by butonic** [comment]
:+1:

**Pull request merged**
