### PR TITLE
Index is stored in folder, not file

### LINKED ISSUE #81: Log polluted - Error while running background job: Path exists, but it's not a directory
No need to log this - simple ignore

````
{"reqId":"8RZIxXunfGXAMkGqWHHX","remoteAddr":"::1","app":"no app in context","message":"Error while running background job: Path exists, but it's not a directory","level":3,"time":"2015-04-14T08:11:35+00:00","method":"GET","url":"\/oc\/core\/cron.php"}

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #81

### CODE REVIEW

**Comment by VicDeo** [comment]
@DeepDiver1975

**Comment by VicDeo** [comment]
damn, path  is still incorrect...
only removing registerEncryptionWrapper invocation here https://github.com/owncloud/core/blob/ba9a797eaad9aaeeed7960f03f40593a84096512/lib/base.php#L645 fixes log flooding ATM

 search_lucene is completely broken with that wrapper, because it looks for indexes not in `/path/to/data/$user/lucene_index` but in '/tmp/oc_tmp_085cfb0c5deca4da05894aaee8304088'

This PR resolves the issue with path to index but path to the user files is resolved as 
`/path/to/data/$user/files/tmp/oc_tmp_085cfb0c5deca4da05894aaee8304088.ext' that is far from correct

**Comment by DeepDiver1975** [comment]
Well ... the heavy lifting (index generation) is done in background jobs - files cannot be open in this case and indexing them is kind of pointless.

@butonic did this ever work in the scope of encryption? THX

**Comment by VicDeo** [comment]
@DeepDiver1975 README says "no" https://github.com/owncloud/search_lucene/blob/master/README.md

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 README says "no" https://github.com/owncloud/search_lucene/blob/master/README.md

THX - I suggest to get the file info of the file in question and in case the file is encrypted abort any kind of index operation

**Comment by butonic** [comment]
actually, encrypted files were indexed when you were logged in in the web interface and clicked in the search input. you would see the spinner and he would index as long as the page was open ... but background jobs would try to index as well ... failing because the keys were not unlocked ... that just confused users.

**Comment by DeepDiver1975** [comment]
@VicDeo what are the next steps here? We need to get this sorted out. THX

**Comment by VicDeo** [comment]
@DeepDiver1975 
>I suggest to get the file info of the file in question and in case the file is encrypted abort any kind of index operation

it's not encrypted. It is uploaded recently and encryption app is disabled. Wrapper returns path relative to `/tmp` for ANY file making indexing unusable.
Good news is rare these days but this PR really fixes  flooding the log with the message in question (#81)

**Comment by VicDeo** [comment]
@butonic @DeepDiver1975 this one needs to be merged ASAP
my :crystal_ball: and the following snippet
```
$job = new OCA\Search_Lucene\Jobs\IndexJob();
$job->run(['user'=>'AnyUserHere']);
```
tell me that it's a true fix for
exception

**Comment by VicDeo** [comment]
I'm tired to patch it manually for all branches with recent core master.
Merging.

**Pull request merged**
