### PR TITLE
Fix exception thrown while indexing pdf

### PR DESCRIPTION
**Pull request by VicDeo**
https://github.com/owncloud/search_lucene/blob/master/lucene/notindexedexception.php#L12

### CODE REVIEW

**Comment by VicDeo** [comment]
Stable8  is affected:
https://github.com/owncloud/search_lucene/blob/stable8/document/pdf.php#L14

**Comment by karlitschek** [comment]
nice fix :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by VicDeo** [comment]
@karlitschek backporting requested

**Comment by karlitschek** [comment]
please backport. Thanks

**Pull request merged**
